
name: Node.js with ngrok

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: npm install
    
    - run: nohup npm start &  # Starts your Node.js API in the background
    
    - name: Install ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update
        sudo apt-get install ngrok
    
    - name: Start ngrok with authtoken
      run: |
        nohup ngrok http 3000 --authtoken ${{ secrets.NGROK_AUTH_TOKEN }} > ngrok.log &
        sleep 10
    
    - name: Get ngrok URL
      run: |
        curl --silent http://localhost:4040/api/tunnels > tunnels.json
        NGROK_URL=$(jq -r '.tunnels[0].public_url' tunnels.json)
        echo "Your public API URL is: $NGROK_URL"

    - name: Keep the job alive for 6 hours
      run: sleep 21600  # Keeps the workflow alive for 6 hours
