name: Node.js CI with Database Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # Every 5 hours and 58 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start the application
      run: |
        npm start &
        sleep 15  # Wait for the server to start

    - name: Start a temporary web server
      run: |
        python3 -m http.server 8000 --directory includes &
        sleep 5  # Give the server some time to start

    - name: Download updated data.sqlite
      run: |
        curl -o includes/data.sqlite http://localhost:8000/data.sqlite

    - name: Commit and push updated database
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add includes/data.sqlite
        git commit -m "Update data.sqlite file"
        git push
