name: Node.js CI with Database Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/1 * * * *'  # Every minute, for testing purposes

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start the application
      run: |
        npm start &
        echo "Application started"
        sleep 15  # Wait for the server to start

    - name: Start a temporary web server
      run: |
        python3 -m http.server 8000 --directory includes &
        echo "Temporary server started"
        sleep 5  # Give the server some time to start

    - name: Wait for 1 minute
      run: |
        echo "Waiting for 1 minute before updating database"
        sleep 60  # Sleep for 1 minute (60 seconds)

    - name: Download updated data.sqlite
      run: |
        curl --retry 5 --retry-delay 10 --retry-max-time 60 -o includes/data.sqlite "http://localhost:8000/sqlite?apikey=priyansh-here"
        echo "Database file updated"

    - name: Commit and push updated database
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add includes/data.sqlite
        git commit -m "Update data.sqlite file"
        git push
        echo "Database file committed and pushed"

    - name: Keep the workflow alive for 6 hours
      run: |
        echo "Workflow is running..."
        sleep 60  # Keep the workflow alive for an additional minute to complete
